[versions]
ldlib2 = "2.2.37"
registrate = "MC1.21-1.3.0+67"

jei = "19.39.0.372"
emi = "1.1.22+1.21.1"


## modrinth maven ##
jade = "15.10.0+neoforge"
sodium = "mc1.21.1-0.6.13-neoforge"
iris = "1.8.8+1.21.1-neoforge"
modernfix = "4SPHwiDB" # 5.24.3+mc1.21.1
modernui = "3.12.0.2"

## curseforge maven ##
spark = "6225208"

## libs ##


[libraries]
ldlib2              = { module = "com.lowdragmc.ldlib2:ldlib2-neoforge-1.21.1", version.ref = "ldlib2" }
registrate          = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }

jei-common-api      = { module = "mezz.jei:jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api    = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge-impl   = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
emi                 = { module = "dev.emi:emi-neoforge", version.ref = "emi" }

jade                = { module = "maven.modrinth:jade", version.ref = "jade" }
sodium              = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris                = { module = "maven.modrinth:iris", version.ref = "iris" }
modernui            = { module = "maven.modrinth:modern-ui", version.ref = "modernui" }
modernfix           = { module = "maven.modrinth:modernfix", version.ref = "modernfix" }

spark               = { module = "curse.maven:spark-361579", version.ref = "spark" }
[bundles]
jei = ["jei-common-api", "jei-neoforge-api", "jei-neoforge-impl"]