// -*- coding: utf-8 -*-
package com.modularmc.ten.data;

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.nio.file.Path;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

import static org.junit.jupiter.api.Assertions.*;

/**
 * GREEN contract test for language data generation parity.
 * <p>
 * Verifies that all language keys are generated by DataGen,
 * EN and ZH key sets are identical, and the main lang directory
 * contains no hand-written files.
 * <p>
 * Requirements validated:
 * <ul>
 *   <li>en_us and zh_cn key sets are identical (diff = 0)</li>
 *   <li>Main mod lang directory is empty (no hand-written JSON)</li>
 *   <li>Generated locales are exactly en_us + zh_cn</li>
 *   <li>All 38 block keys (block + flat) exist in both locales</li>
 *   <li>Items, fluids, tags, JEI, Knowledge entries exist in both locales</li>
 * </ul>
 */
class LangDataGenerationContractTest {

    private static final Path GENERATED_DIR = Path.of(
            "src", "generated", "resources", "assets", "kenergyengineering", "lang");
    private static final Path MAIN_LANG_DIR = Path.of(
            "src", "main", "resources", "assets", "kenergyengineering", "lang");

    /** Expected 38 block IDs registered in {@link com.modularmc.ten.common.data.TENBlocks}. */
    private static final Set<String> EXPECTED_BLOCK_IDS = Set.of(
            "tin_ore", "nickel_ore", "deep_tin_ore", "deep_nickel_ore",
            "tin_block", "nickel_block", "powered_tin_block", "chlorium_block",
            "raw_tin_block", "raw_nickel_block",
            "machine_smelter", "machine_pulverizer", "machine_compressor", "machine_refiner",
            "machine_induction_furnace", "machine_psionicant", "machine_beacon_simulator",
            "machine_mob_ripper", "machine_quarry", "machine_enchantment_flusher",
            "machine_matter_condenser", "machine_farm_manager",
            "engine_extraction", "engine_metal", "engine_biomass", "engine_solar",
            "cable", "cable_quartz", "cable_azure", "cable_star",
            "pipe", "pipe_white", "pipe_black",
            "energy_cell", "creative_energy_cell",
            "channel_energy", "channel_item", "channel_fluid"
    );

    // ════════════════════════════════════════════════════════════════
    // Helpers — read generated JSON
    // ════════════════════════════════════════════════════════════════

    private static Map<String, String> readJson(String locale) {
        var file = GENERATED_DIR.resolve(locale + ".json").toFile();
        try (var reader = new FileReader(file, java.nio.charset.StandardCharsets.UTF_8)) {
            var obj = JsonParser.parseReader(reader).getAsJsonObject();
            return StreamSupport.stream(obj.entrySet().spliterator(), false)
                    .collect(Collectors.toMap(
                            Map.Entry::getKey,
                            e -> e.getValue().getAsString()));
        } catch (Exception e) {
            throw new RuntimeException("Failed to read generated " + locale + ".json", e);
        }
    }

    // ════════════════════════════════════════════════════════════════
    // 1. Key set parity — en_us must have exactly the same keys as zh_cn
    // ════════════════════════════════════════════════════════════════

    @Test
    void enUsAndZhCnHaveIdenticalKeySets() {
        var en = readJson("en_us");
        var zh = readJson("zh_cn");

        var enKeys = new TreeSet<>(en.keySet());
        var zhKeys = new TreeSet<>(zh.keySet());

        var onlyEn = new TreeSet<>(enKeys);
        onlyEn.removeAll(zhKeys);
        var onlyZh = new TreeSet<>(zhKeys);
        onlyZh.removeAll(enKeys);

        // GREEN phase: en_us and zh_cn must have identical key sets
        assertTrue(onlyEn.isEmpty(),
                "Keys only in en_us (expected 0): " + onlyEn);
        assertTrue(onlyZh.isEmpty(),
                "Keys only in zh_cn (expected 0): " + onlyZh);
    }

    // ════════════════════════════════════════════════════════════════
    // 2. Main lang directory must be empty
    // ════════════════════════════════════════════════════════════════

    @Test
    void mainLangDirectoryIsEmpty() {
        var dir = MAIN_LANG_DIR.toFile();
        if (dir.exists()) {
            var files = dir.listFiles();
            assertTrue(files == null || files.length == 0,
                    "Main lang dir should be empty, found: "
                            + (files != null ? java.util.Arrays.toString(files) : "null"));
        }
        // If dir doesn't exist, that's also fine — means no hand-written lang files
    }

    // ════════════════════════════════════════════════════════════════
    // 3. Generated locales are exactly en_us + zh_cn
    // ════════════════════════════════════════════════════════════════

    @Test
    void generatedLocalesAreExactlyEnUsAndZhCn() {
        var dir = GENERATED_DIR.toFile();
        assertTrue(dir.exists(), "Generated lang dir must exist");
        var files = dir.listFiles();
        assertNotNull(files, "Generated lang dir should have files");

        var jsonFiles = java.util.Arrays.stream(files)
                .filter(f -> f.getName().endsWith(".json"))
                .map(f -> f.getName().replace(".json", ""))
                .collect(Collectors.toSet());

        assertEquals(Set.of("en_us", "zh_cn"), jsonFiles,
                "Only en_us.json and zh_cn.json should exist in generated lang dir");
    }

    // ════════════════════════════════════════════════════════════════
    // 4. All 38 block keys exist in both locales (block + flat forms)
    // ════════════════════════════════════════════════════════════════

    @Test
    void allBlockKeysExistInBothLocales() {
        var en = readJson("en_us");
        var zh = readJson("zh_cn");

        for (String id : EXPECTED_BLOCK_IDS) {
            String blockKey = "block.kenergyengineering." + id;
            String flatKey = "kenergyengineering." + id;

            assertTrue(en.containsKey(blockKey),
                    "EN missing block key: " + blockKey);
            assertTrue(zh.containsKey(blockKey),
                    "ZH missing block key: " + blockKey);
            assertTrue(en.containsKey(flatKey),
                    "EN missing flat key: " + flatKey);
            assertTrue(zh.containsKey(flatKey),
                    "ZH missing flat key: " + flatKey);
        }
    }

    // ════════════════════════════════════════════════════════════════
    // 5. Item keys parity spot-check
    // ════════════════════════════════════════════════════════════════

    @Test
    void itemKeysExistInBothLocales() {
        var en = readJson("en_us");
        var zh = readJson("zh_cn");

        // Spot-check some representative items
        for (String itemKey : new String[]{
                "item.kenergyengineering.tin_ingot",
                "item.kenergyengineering.spanner",
                "item.kenergyengineering.mould_gear",
                "item.kenergyengineering.augmented_levelup",
                "item.kenergyengineering.liquid_xp_bucket"
        }) {
            assertTrue(en.containsKey(itemKey), "EN missing item key: " + itemKey);
            assertTrue(zh.containsKey(itemKey), "ZH missing item key: " + itemKey);
        }
    }
}
